import oficinaImg from "@/assets/imagen oficina.png";

const SectionEstudio = () => {
  return (
      <section id="estudio" className="py-20 bg-background">
            <div className="container-main">
                    <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
                              {/* Texto */}
                                        <div className="space-y-6">
                                                    <p className="text-sm font-medium tracking-widest text-primary uppercase">
                                                                  El Estudio
                                                                              </p>
                                                                                          <h2 className="text-3xl md:text-4xl font-serif font-medium leading-tight">
                                                                                                        Defensa penal estratégica y técnica
                                                                                                                    </h2>
                                                                                                                                <div className="space-y-4 text-muted-foreground leading-relaxed">
                                                                                                                                              <p>
                                                                                                                                                              Formamos parte de un estudio especializado exclusivamente en derecho penal, con más de 12 años de experiencia y sólida formación académica y profesional.
                                                                                                                                                                            </p>
                                                                                                                                                                                          <p>
                                                                                                                                                                                                          Trabajamos cada caso con el rigor y la dedicación que merece. Contamos con un equipo de profesionales que interviene en cada instancia, permitiendo un abordaje integral para respetar rigurosamente los derechos y garantías de nuestros clientes.
                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                      Atendemos urgencias las 24 horas en toda la provincia de Entre Ríos y jurisdicciones federales.
                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                    {/* Foto */}
                                                                                                                                                                                                                                                                                                              <div className="relative">
                                                                                                                                                                                                                                                                                                                          <img
                                                                                                                                                                                                                                                                                                                                        src={oficinaImg}
                                                                                                                                                                                                                                                                                                                                                      alt="Estudio Meglio & Chemez"
                                                                                                                                                                                                                                                                                                                                                                    className="w-full h-[500px] object-cover rounded-sm"
                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                            </section>
                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                              export default SectionEstudio;